export const PHASE_NAMES: Record<number, string> = {
  0: "Go as a Language",
  1: "Structs, Methods & Data Modeling",
  2: "Pointers & Memory Basics",
  3: "Error Handling as Design",
  4: "Interfaces (Core Abstraction)",
  5: "Composition over Inheritance",
  6: "Collections & Data Structures",
  7: "Generics (Carefully)",
  8: "Testing & Tooling",
  9: "Concurrency Fundamentals",
  10: "Synchronization & Coordination",
  11: "Context & Lifecycles",
  12: "Memory, Performance & GC Awareness",
  13: "Files, Networking & IO",
  14: "Building Web Services",
  15: "Advanced Concurrency Patterns",
  16: "Advanced Systems Patterns",
};
